### PR TITLE
feat: add package for Couchbase Lite based stores

### PR DESCRIPTION
**Pull request by blaugold**
## Status
**READY*

## Breaking Changes
NO

## Description
This PR adds a package which implements support for Couchbase Lite based stores.

## Related PRs
N/A

## Todos
- [x] Tests
- [x] Documentation
- [x] Examples

## Steps to Test or Reproduce
```
cd package/stash_cbl
dart test
```

## Impact to Remaining Code Base
This PR will affect:

* coverage

### CODE REVIEW

**Comment by ivoleitao** [comment]
Thanks a lot for your contribution @blaugold 🥇  I'll start the review as soon as possible targeting next weekend as the release date. I'm adding support for Isar as well and this contribution will complement the backend support even further

**Comment by blaugold** [comment]
Thank you for your work on this project! Looking forward to the review and getting the PR ready for merging :)

**Review by ivoleitao — COMMENTED** [review]
First of all you fully grasped the way the library works, that's awesome. For the most part it seems fine but I do have a doubt.

Is there a reason to do not abstract this call:

```
 // Initialize Couchbase Lite for standalone Dart.
 await CouchbaseLiteDart.init(edition: Edition.community);
```

inside the `final store = await newCblLocalCacheStore(path: path, fromEncodable: (json) => Task.fromJson(json));` ?

I did something similar in the sqlite and this was one of the reasons I created the build pattern returning a Future in the adapters with a private constructor

I may not be understanding this fully and perhaps this really needs to be separate to allow other use cases where we may even need additional dependencies. Dependencies that we don't want to add directly eventually...

I don't know this library that well as you do so I'm fine otherwise.

**Comment by blaugold** [comment]
> I may not be understanding this fully and perhaps this really needs to be separate to allow other use cases where we may even need additional dependencies. Dependencies that we don't want to add directly eventually...

That's precisely the reason why we can't make the `init` call for the user. The API for Couchbase Lite is in the `cbl` package. The native libraries for use with Flutter are provided through a Flutter plugin (`cbl_flutter`) and for use with standalone Dart there is the `cbl_dart` package. The initialization of Couchbase Lite is a bit different between Flutter and standalone Dart and supports different options.

**Comment by ivoleitao** [comment]
> > I may not be understanding this fully and perhaps this really needs to be separate to allow other use cases where we may even need additional dependencies. Dependencies that we don't want to add directly eventually...
> 
> That's precisely the reason why we can't make the `init` call for the user. The API for Couchbase Lite is in the `cbl` package. The native libraries for use with Flutter are provided through a Flutter plugin (`cbl_flutter`) and for use with standalone Dart there is the `cbl_dart` package. The initialization of Couchbase Lite is a bit different between Flutter and standalone Dart and supports different options.

Ok got it. That's what I though

**Comment by ivoleitao** [comment]
I will work on to released it during next weekend. Once again thanks a lot for your contribution

**Pull request merged**
